# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
#   - jekyll-remote-theme
# title: [JetHub]
# description: [Делаем ML инструменты для повышения эффективности процесса DevSecOps]

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: [JetHub]
description: [Делаем ML инструменты для повышения эффективности процесса DevSecOps]
